[package]
name = "p347_largest_integer_divisible_by_two_primes"
version = "0.0.1"
authors = ["Emerentius <Emerentius@arcor.de>"]

[dependencies.euler_utils]
path="../euler_utils"

[dependencies.primal]
