[package]
name = "381_prime_min_k_factorial"
version = "0.1.0"
authors = ["Emerentius <Emerentius@arcor.de>"]

[dependencies.euler_tools]
path = "../../libraries/euler_tools"
version = "0.1.0"

[dependencies]
primal = "0.2"
