[package]

name = "p069_totient_maximum"
version = "0.0.1"
authors = ["Emerentius <Emerentius@arcor.de>"]

[dependencies.num]
version = "*"

[dependencies.euler_utils]
path = "../euler_utils"
version = "0.1"
