[package]
name = "118_pandigital_prime_sets"
version = "0.1.0"
authors = ["Emerentius <Emerentius@arcor.de>"]

[dependencies.my_combinatorics]
path = "../../libraries/my_combinatorics"
version = "0.1"

[dependencies]
primal = "0.2"
